import { Response } from 'express';
import { AuthRequest } from '../middleware/auth';
import { createNotification, deleteNotification, listNotifications, markAllNotificationsRead, markNotificationRead } from '../services/notificationService';

const context = (req: AuthRequest) => ({ userId: req.user!.id, organizationId: req.user!.organizationId });
const parseId = (value: string | string[]) => { const id = Number(Array.isArray(value) ? value[0] : value); return Number.isInteger(id) && id > 0 ? id : null; };
export async function readAll(req: AuthRequest, res: Response) { const owner = context(req); await markAllNotificationsRead(owner.userId, owner.organizationId); return res.json({ message: 'Tüm bildirimler okundu olarak işaretlendi' }); }
export async function list(req: AuthRequest, res: Response) { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 20)); const owner = context(req); const result = await listNotifications(owner.userId, owner.organizationId, page, limit); const notifications = result.items.map(item => ({ id: item.id, user_id: item.userId, message: item.message, read: item.read ? 1 : 0, created_at: item.createdAt })); return res.json({ notifications, unreadCount: result.unreadCount, pagination: { total: result.total, page, limit, totalPages: Math.ceil(result.total / limit) } }); }
export async function create(req: AuthRequest, res: Response) { const message = String(req.body?.message || '').trim(); if (!message) return res.status(400).json({ error: 'message zorunludur' }); const owner = context(req); return res.status(201).json(await createNotification(owner.userId, owner.organizationId, message)); }
export async function readOne(req: AuthRequest, res: Response) { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: 'Geçersiz bildirim numarası' }); const owner = context(req); if (!await markNotificationRead(id, owner.userId, owner.organizationId)) return res.status(404).json({ error: 'Bildirim bulunamadı' }); return res.json({ message: 'Bildirim okundu olarak işaretlendi' }); }
export async function remove(req: AuthRequest, res: Response) { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: 'Geçersiz bildirim numarası' }); const owner = context(req); if (!await deleteNotification(id, owner.userId, owner.organizationId)) return res.status(404).json({ error: 'Bildirim bulunamadı' }); return res.json({ message: 'Bildirim silindi' }); }
