import React, { useEffect, useState } from 'react';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import { disableMfa, enableMfa, getUser, setupMfa } from '../services/api';
import './SecurityPage.css';

export default function SecurityPage() {
  const [user,setUser]=useState(null); const [setup,setSetup]=useState(null); const [code,setCode]=useState(''); const [password,setPassword]=useState(''); const [backupCodes,setBackupCodes]=useState([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const refreshUser=async()=>{const result=await getUser();setUser(result.user);localStorage.setItem('authUser',JSON.stringify(result.user));};
  useEffect(()=>{refreshUser().catch(()=>setError('Güvenlik bilgileri alınamadı.')).finally(()=>setLoading(false));},[]);
  const run=async action=>{setBusy(true);setError('');setMessage('');try{await action();}catch(requestError){setError(requestError.response?.data?.error||'İşlem tamamlanamadı.');}finally{setBusy(false);}};
  const beginSetup=()=>run(async()=>{setSetup(await setupMfa());setBackupCodes([]);setMessage('Doğrulayıcı uygulamanıza aşağıdaki anahtarı ekleyin.');});
  const confirmSetup=event=>{event.preventDefault();run(async()=>{const result=await enableMfa(code);setBackupCodes(result.backupCodes||[]);setSetup(null);setCode('');await refreshUser();setMessage('İki aşamalı doğrulama etkinleştirildi. Yedek kodları güvenli bir yerde saklayın.');});};
  const turnOff=event=>{event.preventDefault();run(async()=>{await disableMfa(password);setPassword('');setBackupCodes([]);await refreshUser();setMessage('İki aşamalı doğrulama kapatıldı.');});};
  const copyCodes=async()=>{await navigator.clipboard.writeText(backupCodes.join('\n'));setMessage('Yedek kodlar panoya kopyalandı.');};
  return <div className="security-page"><Sidebar/><div className="security-content"><Navbar user={user}/><main className="security-main"><h1>Güvenlik ve Yedekleme</h1><p className="security-lead">Hesabınız için iki aşamalı doğrulama ayarlarını yönetin.</p>{loading?<div className="security-card">Güvenlik bilgileri yükleniyor…</div>:<div className="security-grid"><section className="security-card"><div className="security-card-heading"><div><h2>İki Aşamalı Doğrulama</h2><p>Şifrenize ek olarak doğrulayıcı uygulamadaki tek kullanımlık kod istenir.</p></div><span className={`security-status ${user?.mfaEnabled?'enabled':''}`}>{user?.mfaEnabled?'Etkin':'Kapalı'}</span></div>{!user?.mfaEnabled&&!setup&&<button className="security-primary" onClick={beginSetup} disabled={busy}>Kurulumu Başlat</button>}{setup&&<form onSubmit={confirmSetup} className="security-form"><div className="security-steps"><strong>1. Doğrulayıcı uygulamanızı açın.</strong><span>Google Authenticator, Microsoft Authenticator veya uyumlu bir uygulama kullanabilirsiniz.</span><strong>2. Kurulum anahtarını ekleyin.</strong><code>{setup.secret}</code><strong>3. Uygulamada oluşan 6 haneli kodu girin.</strong></div><label htmlFor="mfa-code">Doğrulama kodu</label><input id="mfa-code" inputMode="numeric" value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,'').slice(0,6))} required/><div className="security-actions"><button className="security-primary" disabled={busy||code.length!==6}>Etkinleştir</button><button type="button" className="security-secondary" onClick={()=>{setSetup(null);setCode('');}}>İptal</button></div></form>}{user?.mfaEnabled&&<form onSubmit={turnOff} className="security-form"><label htmlFor="mfa-password">MFA'yı kapatmak için mevcut şifreniz</label><input id="mfa-password" type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" required/><button className="security-danger" disabled={busy}>İki Aşamalı Doğrulamayı Kapat</button></form>}</section>{backupCodes.length>0&&<section className="security-card backup-card"><h2>Yedek Kodlar</h2><p>Telefonunuza erişemediğinizde bu kodlardan birini kullanabilirsiniz. Her kod yalnızca bir kez çalışır.</p><div className="backup-codes">{backupCodes.map(item=><code key={item}>{item}</code>)}</div><button className="security-secondary" onClick={copyCodes}>Kodları Kopyala</button></section>}</div>}{message&&<div className="security-message success">{message}</div>}{error&&<div className="security-message error">{error}</div>}</main></div></div>;
}
